theme: jekyll-theme-cayman
title: TreZe bits
description:  >- 
    Una colección más de cuadernos de apuntes sobre programación y ordenadores.<br>
    &copy; 2025. El taller de Félix.<br><br>
    "<i>If you give someone a program, you will frustrate them for a day; <br>
    if you teach them to program, you will frustrate them for a lifetime.</i>"

